### ISSUE TITLE
README_ASSETS

### ISSUE THREAD

**Issue by terasakisatoshi** [AtelierArith/Replay.jl#1]

**Comment by terasakisatoshi** [comment]
![demo](https://user-images.githubusercontent.com/16760547/141813986-d662f944-3377-40ca-872e-b2796dbc3102.gif)

![redirect_output](https://user-images.githubusercontent.com/16760547/141814010-ac335f23-1348-4cba-8f17-6fdf4621efe9.gif)

**Comment by terasakisatoshi** [comment]
https://user-images.githubusercontent.com/16760547/142023878-749e39a9-7b60-4db1-b6a0-df440b31c432.mov

**Comment by terasakisatoshi** [comment]
![demo](https://user-images.githubusercontent.com/16760547/142026114-15029088-4f3e-4404-beba-e544f3a5a667.gif)

**Comment by hyrodium** [comment]
We are now using asciinema in the README.md file, so it seems we can close this issue.
