### ISSUE TITLE
write docs

### ISSUE THREAD

**Issue by terasakisatoshi** [AtelierArith/Replay.jl#3]

**Comment by hyrodium** [comment]
I think this issue can be closed after resolving the following.

- [x] Add docstrings to `replay` methods (#61)
- [ ] Move documentation from `README.md` to `docs/src/*.md`
- [x] Add an example page to the docs (#54)

**Comment by hyrodium** [comment]
Can I move all documentation in `README.md` to `docs/src/index.md`? Or should I keep some documentation in `README.md`?

**Comment by terasakisatoshi** [comment]
> Can I move all documentation in `README.md` to `docs/src/index.md`? Or should I keep some documentation in `README.md`?

👍
