### ISSUE TITLE
Use `cmd::Cmd` instead of `cmd::String` in `replay` funciton

### ISSUE THREAD

**Issue by hyrodium** [AtelierArith/Replay.jl#62]
[The current implementation](https://github.com/AtelierArith/Replay.jl/blob/56dd22ef531d775d3f44e8715d21167eebe065ba/src/Replay.jl#L118) uses `cmd="--color=yes"` as a keyword argument, but it seems `` cmd::Cmd=`--color=yes` `` is better because we can remove `split` in [this line](https://github.com/AtelierArith/Replay.jl/blob/56dd22ef531d775d3f44e8715d21167eebe065ba/src/Replay.jl#L87).

```julia
julia> cmd = "--color=yes -q"
"--color=yes -q"

julia> `julia $(split(cmd))`
`julia --color=yes -q`

julia> cmd = `--color=yes -q`
`--color=yes -q`

julia> `julia $cmd`
`julia --color=yes -q`
```

**Comment by terasakisatoshi** [comment]
This makes sense to me.

If this proposal is merged, I think it should be released as a v0.5 feature. This would be a destructive change for users who pass an object (type String) to the "cmd" argument.
