### ISSUE TITLE
`LiveServer.servedocs()` creates cast files infinite times.

### ISSUE THREAD

**Issue by terasakisatoshi** [AtelierArith/Replay.jl#65]
My workflow includes running `LiveServer.servedocs` to check that our documentation is created as planned.

It seems `LiveServer.servedocs` function calls `docs/make.jl` in the background. Therefore [generate_example_page(sections)](https://github.com/AtelierArith/Replay.jl/blob/d7af2a6d0fea36d06a79e29e7479a9d51c7d28b4/docs/make.jl#L111) is called infinite times, which creates all cast files even though they are already in docs/assets.

Adding a conditional branch to check a specified cast file is created is a good idea.

This is my homework.

**Comment by hyrodium** [comment]
Should we add an option like `overwrite_cast` or `skip_existing_cast`?

**Comment by terasakisatoshi** [comment]
🤔  Where can i find the option? > `skip_existing_cast`

**Comment by hyrodium** [comment]
Oh, sorry for not being clear enough. I was thinking of adding a keyword argument `skip_existing_cast` to `generate_example_page` in `docs/make.jl` not to regenerate the cast files.
